"""
Runs the required retrieval-test queries against the KB and writes a
markdown log with: query, retrieved chunk, source, relevance explanation,
and a verdict slot (correct / partially correct / incorrect) for the
human reviewer to fill in after reading the actual retrieved content.

Run: python -m retrieval_tests.run_retrieval_tests
"""
from config import settings
from question_2_kb.embedder import KnowledgeBaseEmbedder

# One query per required category: product, policy, qualification, FAQ, objection.
# Matches retrieval_tests/retrieval_test_log.md exactly — this script
# regenerates that file; edit queries here, not there.
TEST_QUERIES = [
    ("product", "How is my motor insurance premium calculated?", "Motor Insurance Premium Structure"),
    ("policy", "What's the waiting period for pre-existing conditions on my health policy?", "Health Insurance Waiting Periods"),
    ("qualification", "What payment methods can I use to renew?", "Renewal Payment Channels"),
    ("faq", "What happens if I miss my renewal payment deadline?", "Auto Policy Grace Period"),
    ("objection", "This renewal is too expensive, why should I stay with this insurer?", "NCB discount angle, or a correctly-declined no-match — genuine edge case"),
]


def run():
    embedder = KnowledgeBaseEmbedder()
    rows = [
        f"*Generated by `run_retrieval_tests.py`. RETRIEVAL_SCORE_THRESHOLD "
        f"is currently `{settings.RETRIEVAL_SCORE_THRESHOLD}` — if that's "
        f"still 0.20, treat any 'correct' verdict below skeptically until "
        f"you've raised it and re-run, since a loose threshold can let a "
        f"wrong document through looking grounded.*\n"
    ]

    for category, query, expected in TEST_QUERIES:
        result = embedder.search_grounded_context(query)

        if result is None:
            rows.append(
                f"### [{category}] {query}\n"
                f"- Expected match: {expected}\n"
                f"- Retrieved: **none** (below similarity threshold)\n"
                f"- Source: n/a\n"
                f"- Relevance: no chunk in the KB clears the confidence threshold for this query\n"
                f"- Verdict: fill in — correct if this SHOULD have no match (genuine coverage gap), incorrect if it should have matched something\n"
            )
            continue

        rows.append(
            f"### [{category}] {query}\n"
            f"- Expected match: {expected}\n"
            f"- Retrieved chunk: {result['content']}\n"
            f"- Source: {result['source']} (record_id: {result['record_id']}, score: {result['score']})\n"
            f"- Relevance: fill in — does the chunk actually answer the question asked, or just share keywords?\n"
            f"- Verdict: fill in — correct / partially correct / incorrect\n"
        )

    output = "# Retrieval Test Log\n\n" + "\n".join(rows)
    with open("retrieval_tests/retrieval_test_log.md", "w") as f:
        f.write(output)
    print(output)


if __name__ == "__main__":
    run()
